name: PR ACTION

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: pr-action-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Check format
        run: npm run format:all
      - name: Lint code
        run: npm run lint:all
      - name: Prepare
        run: npm run prepare
      - name: Build the React app
        run: npm run build
