name: PR ACTION

on:
    pull_request:
        types: [opened, synchronize]
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Check format
              run: npm run format:all

            - name: Lint code
              run: npm run lint:all

            - name: Prepare
              run: npm run prepare

            - name: Build the React app
              run: npm run build
